### ISSUE TITLE
New syntax proposal for accessing instance attributes

### ISSUE THREAD

**Issue by HashLDash** [HashLDash/Photon#11]
Photon currently uses the 'self' name to identify the class instance.

The proposed alternative (or optional) notation is:
.attribute = 2
Instead of
self.attribute = 2

**Comment by eualexdev** [comment]
Eu preferia com o self 
Mas claro minha opinião não importa

**Comment by EdMartinezNunes** [comment]
bem se não vai alterar no desempenho o explicito é melhor implicito.

**Comment by ntaraujo** [comment]
altera no desempenho do programador

**Comment by HashLDash** [comment]
Eu pretendo deixar essa notação opcional.

**Comment by Huyston** [comment]
Implementado no commit 6ae9159
