### ISSUE TITLE
Function and Variable Names

### ISSUE THREAD

**Issue by juanjavatus** [HashLDash/Photon#140]
I know is your way of naming, I follow you time ago, but is not very 'pep'...

[Function and Variable Names](https://peps.python.org/pep-0008/#function-and-variable-names)

Function names should be lowercase, with words separated by underscores as necessary to improve readability.

Variable names follow the same convention as function names.

**mixedCase** is allowed only in contexts where that’s already the prevailing style (e.g. threading.py), to retain backwards compatibility.

**Comment by HashLDash** [comment]
Yea, I don't like PEP8. I created a code guideline here. Maybe someday I'll change this. But not in a near future. I don't mind if someone does it tho. But changing it now will require some work and I would rather make more features than attending PEP.

**Comment by juanjavatus** [comment]
Where can I find the code guideline?

**Comment by HashLDash** [comment]
Here -> https://github.com/HashLDash/Photon/blob/main/CODING_GUIDELINES.md
