### ISSUE TITLE
Language name is already being used by other projects

### ISSUE THREAD

**Issue by HashLDash** [HashLDash/Photon#2]
As Marcus Lourenço said in my video on youtube, there are many other references for the term wlang on the internet. This can confuse people into looking into other projects instead. What you think of changing the name of the language. Name and extensions suggestions are welcome ^^

**Comment by HashLDash** [comment]
What about Photon. Looks like Python, but it is lightning fast :D

**Comment by ntaraujo** [comment]
would use `.pt` as extension :) it was just used by an old [scratch modification](http://pantherprogramming.weebly.com/)

**Comment by HashLDash** [comment]
Cool!

**Comment by HashLDash** [comment]
Changed language name to photon!
