### ISSUE TITLE
Extension name

### ISSUE THREAD

**Issue by HashLDash** [HashLDash/Photon#7]
Now that the language name changed to Photon, it's time to reconsider the extension name:
- keep .w
- .p
- .ph
- .pt

What do you think?

**Comment by robertoweller** [comment]
.pt hihi cool

**Comment by eualexdev** [comment]
.pt

**Comment by ntaraujo** [comment]
Some helpful info:

* `.w` was used twice:
1. as the OpenEdge Architect Source Code File
![image](https://user-images.githubusercontent.com/66187211/115120708-3eeb3200-9f85-11eb-9003-e47a71f132c9.png)
Architect is an Eclipse-based IDE, designed to enhance the productivity of OpenEdge developers building ABL applications.
2. as the Google Toolbar Search History File
![image](https://user-images.githubusercontent.com/66187211/115120830-ea948200-9f85-11eb-9cee-0a1bbd764f1c.png)
Google Toolbar is an addon for Internet Explorer bringing the Chrome Toolbar to the browser.

* `.p` was used thrice:
1. as the Python Pickle File
![image](https://user-images.githubusercontent.com/66187211/115121078-2419bd00-9f87-11eb-929d-d28a01b7da9f.png)
Pickle is a Python module implementing protocols for serializing and de-serializing a Python object structure.
2. as the Pascal Source Code File
![image](https://user-images.githubusercontent.com/66187211/115121120-722ec080-9f87-11eb-9bdb-3e334640fb38.png)
Pascal is an imperative and procedural programming language.
3. as the LightWave Plug-in File
![image](https://user-images.githubusercontent.com/66187211/115121257-04cf5f80-9f88-11eb-9b9c-923d293bc1e6.png)
LightWave is a software package used for rendering 3D images, both animated and static.

* `.ph` was used twice:
1. as the Perl Header File
![image](https://user-images.githubusercontent.com/66187211/115121357-ad7dbf00-9f88-11eb-9c41-071931edc680.png)
Perl is a family of two high-level, general-purpose, interpreted, dynamic programming languages.
2. as the AOL Phone Home Settings File
![image](https://user-images.githubusercontent.com/66187211/115122100-83c69700-9f8c-11eb-8ecf-04c8aec4feb2.png)
AOL is an American web portal and online service provider based in New York City.

* `.pt` was used once:
1. as the Panther Project File
![image](https://user-images.githubusercontent.com/66187211/115121778-e28b1100-9f8a-11eb-9614-9b46c7fb57f1.png)
Panther is a Scratch modification, a visual programming toolkit used to create small interactive games.


From these, I would consider 

a problem:
* `.p` - the Pickle use, as it is extensively used in Python
* `.ph` - the Perl use, as it is between [the most used languages](https://pypl.github.io/PYPL.html)

not a considerable problem:
* `.w` - the Architect use, so especific
* `.p` - the Pascal use, still used, but no more common
* `.p` - the LightWave use, not directly related with programming

and old as hell:
* `.w` - the Google Toolbar use. See its [official page](https://www.google.com/intl/en-US/toolbar/ie/index.html)
* `.ph` - the AOL use. See the [comercial of AOL6](https://www.youtube.com/watch?v=Vulk0uVO7qw)
* `.pt` - the Panther use. See its [official page](http://pantherprogramming.weebly.com/index.html)

I just think pt has a little shade of red and ph remembers me chemistry :P

**Comment by HashLDash** [comment]
I think .p is the least problematic.

Pickle is mostly used as .pkl
Pascal is mostly used as .pas
LightWave? Not a concern.

**Comment by robertoweller** [comment]
And if  use `.pw`?

**Comment by ntaraujo** [comment]
I forgot to mention that `.p` is also used by MATLAB binary run-time files

But at all, i think `.p` is a good choice. It is more beautiful too kk

If in some specific conflict cases, the person could just rename his files with `.ph` or `.photon` as these other languages do

**Comment by HashLDash** [comment]
Here is a list of programming language extensions. [list](https://gist.github.com/ppisarczyk/43962d06686722d26d176fad46879d41)

search for .ext" and you will get all languages with the ext extension

.pho is not in this list, for example.

**Comment by robertoweller** [comment]
# I created a program that can help you choose a name.

Criei um programa que pode ajudá-lo a escolher um nome.

Ele procura o formato do arquivo.
It looks for the file format.

Just run this command. Basta executar este comando :
```
git clone https://github.com/robertoweller/acha_formato.git
cd acha_formato/
python3 main.py
```

or 
Looking for or [downloading](https://github.com/robertoweller/acha_formato.git) from my repository, I did it based on what @HashLDash Presents.

ou
Procurando ou [baixar](https://github.com/robertoweller/acha_formato.git) do meu repositório, fiz com baseado no que @HashLDash  apresentou.

I hope it will be useful to someone.

**Comment by robertoweller** [comment]
Testando aqui, `.pn` não tem.

Testing here, `.pn` doesn’t have

**Comment by robertoweller** [comment]
> Here is a list of programming language extensions. [list](https://gist.github.com/ppisarczyk/43962d06686722d26d176fad46879d41)
> 
> search for .ext" and you will get all languages with the ext extension
> 
> .pho is not in this list, for example.

Nas linhas 101, 1299, 1761 falta "extensions", pode da erro dependendo do jeito que usar, então coloquei um `"extensions": []` vazio só para não dar erro quiser usar está [aqui](https://gist.github.com/robertoweller/ecc12ad79c3c6ef1b8e28039b6d6fca7)

**Comment by HashLDash** [comment]
Acho que .y é interessante.

É utilizado pelo yacc (Yet another compiler compiler). Mas é uma das possíveis extensões e é uma linguagem para compiladores e não é utilizada para linguagens de programação. Além disso é parecido com o símbolo gamma, que é o símbolo do fóton em física.

**Comment by ntaraujo** [comment]
dahora, mas talvez seja pouco intuitivo... como se o python usasse uma extensão .s de snake

**Comment by HashLDash** [comment]
Well, w it is. At least for now.
Thanks for all contribution!
I'll close this, but fell free to reopen if anyone has a good idea.
