### ISSUE TITLE
error call tkinter with other name( import tkinter as tk)

### ISSUE THREAD

**Issue by Noah-felix** [HashLDash/Photon#75]
import tkinter as tk

return:

Ops!! This is a syntax error or a parser error.
Common causes: Missing "," ")" "}"
Cannot convert the token asStatement to a word
This happened in line ph.w:1.
Last parsed line is "

import tkinter as tk

"
Last Parse attempt was:
 ""

**Comment by Huyston** [comment]
This feature is not implemented yet. However import tkinter should work on the "py" target.
