### ISSUE TITLE
GUI library rename

### ISSUE THREAD

**Issue by HashLDash** [HashLDash/Photon#8]
The Wui graphical library (Wlang User Interface) may need to be renamed:
- keep wui
- pui
- ui
- gui
- other?
Currently there is th wui, which provides the basic widgets and App runtime/event loop and wuiGraphics, which provides graphic primitives (drawRect, etc).

**Comment by ntaraujo** [comment]
* phui

**Comment by ntaraujo** [comment]
* prism 🔼

**Comment by HashLDash** [comment]
Following the file extension suggestion of y (for the gamma of the photon), it could be named yui.

**Comment by HashLDash** [comment]
I liked prism.
Will close this and keep wui for now. Feel free to reopen to rejoin the discussion.
